DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSFER;

DROP SEQUENCE IF EXISTS ACCOUNT_ID_SEQ;
DROP SEQUENCE IF EXISTS TRANSFER_ID_SEQ;


CREATE SEQUENCE ACCOUNT_ID_SEQ INCREMENT BY 1 MINVALUE 1000;
CREATE SEQUENCE TRANSFER_ID_SEQ INCREMENT BY 1 MINVALUE 100;


CREATE TABLE ACCOUNT(ID BIGINT DEFAULT ACCOUNT_ID_SEQ.NEXTVAL PRIMARY KEY, OWNER VARCHAR(100), BALANCE DECIMAL(19,2), OPEN_DATE DATETIME);
CREATE TABLE TRANSFER(ID BIGINT DEFAULT TRANSFER_ID_SEQ.NEXTVAL PRIMARY KEY, FROM_ACCOUNT BIGINT, TO_ACCOUNT BIGINT, AMOUNT DECIMAL(19,2), TRANSFER_DATE DATETIME, FOREIGN KEY(FROM_ACCOUNT) REFERENCES ACCOUNT(ID), FOREIGN KEY(TO_ACCOUNT) REFERENCES ACCOUNT(ID));

